-- Seed data for pre-cached repositories

-- Repositories
INSERT INTO repositories (id, owner, name, project_name, tech_stack, url, description, language, stars, overall_health_score, created_at, updated_at) VALUES
(1, 'allanmichaelhender', 'guniea-pig-v2', 'Guinea Pig Portfolio', 'React, TypeScript, Django, Python', 'https://github.com/allanmichaelhender/guniea-pig-v2', 'Guinea Pig Portfolio - Python + React + TS', 'TypeScript', 0, 0.85, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'allanmichaelhender', 'Vantage-Point-ML', 'Vantage Point', 'React, TypeScript, FastAPI, Python', 'https://github.com/allanmichaelhender/Vantage-Point-ML', 'Vantage Point - Python + React + TS', 'TypeScript', 0, 0.78, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'allanmichaelhender', 'hybrid_AI_coach', 'Hybrid Hour', 'React, TypeScript, FastAPI, Python', 'https://github.com/allanmichaelhender/hybrid_AI_coach', 'Hybrid Hour - Python + React + TS', 'TypeScript', 0, 0.82, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'allanmichaelhender', 'allanmichaelhender.github.io', 'Portfolio Website', 'React, TypeScript', 'https://github.com/allanmichaelhender/allanmichaelhender.github.io', 'Portfolio Website - React + TS', 'TypeScript', 0, 0.90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Analyses
INSERT INTO analyses (id, repository_id, commit_hash, analyzed_at, analysis_provider, total_files_analyzed, total_issues_found, critical_count, high_count, medium_count, low_count, info_count, security_count, code_quality_count, performance_count, best_practices_count, maintainability_count, overall_health_score, security_health_score, code_quality_health_score, performance_health_score, analysis_duration_ms, model_version, created_at) VALUES
(1, 1, 'abc123def456', CURRENT_TIMESTAMP, 'deepseek', 25, 8, 0, 2, 3, 2, 1, 2, 3, 1, 1, 1, 0.85, 0.80, 0.85, 0.90, 5000, 'deepseek-coder', CURRENT_TIMESTAMP),
(2, 2, 'def456ghi789', CURRENT_TIMESTAMP, 'deepseek', 30, 12, 1, 3, 4, 3, 1, 4, 4, 2, 1, 1, 0.78, 0.70, 0.80, 0.85, 6000, 'deepseek-coder', CURRENT_TIMESTAMP),
(3, 3, 'ghi789jkl012', CURRENT_TIMESTAMP, 'deepseek', 20, 6, 0, 1, 2, 2, 1, 1, 2, 1, 1, 1, 0.82, 0.85, 0.80, 0.85, 4000, 'deepseek-coder', CURRENT_TIMESTAMP),
(4, 4, 'jkl012mno345', CURRENT_TIMESTAMP, 'deepseek', 15, 4, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0.90, 0.90, 0.90, 0.90, 3000, 'deepseek-coder', CURRENT_TIMESTAMP);

-- Analysis Results
INSERT INTO analysis_results (analysis_id, category, type, severity, file_path, line_number, message, suggestion, explanation, confidence_score, impact_score, effort_score, cwe_id, owasp_category, code_snippet, created_at) VALUES
-- guniea-pig-v2 results
(1, 'SECURITY', 'HARDCODED_SECRET', 'high', 'src/config/api.ts', 15, 'Hardcoded API key detected', 'Use environment variables or a secrets manager', 'API keys hardcoded in source code can be extracted by attackers who gain access to the repository', 0.95, 0.90, 0.30, 'CWE-798', 'A07: Identification and Authentication Failures', 'const API_KEY = ''sk-1234567890abcdef''', CURRENT_TIMESTAMP),
(1, 'SECURITY', 'WEAK_PASSWORD_VALIDATION', 'medium', 'src/utils/auth.ts', 23, 'Weak password validation', 'Implement stronger password requirements (min 12 chars, mixed case, numbers, symbols)', 'Weak password validation allows users to set easily guessable passwords that can be brute-forced', 0.85, 0.70, 0.40, 'CWE-521', 'A07: Identification and Authentication Failures', 'if (password.length < 6) return false', CURRENT_TIMESTAMP),
(1, 'CODE_QUALITY', 'HIGH_CYCLOMATIC_COMPLEXITY', 'medium', 'src/components/Header.tsx', 45, 'Function too long (45 lines)', 'Consider breaking into smaller functions with single responsibilities', 'Long functions are harder to test, maintain, and understand. High cyclomatic complexity increases bug risk', 0.90, 0.50, 0.60, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(1, 'CODE_QUALITY', 'DUPLICATE_CODE', 'low', 'src/services/api.ts', 12, 'Code duplication detected', 'Extract common logic to a utility function', 'Duplicated code increases maintenance burden', 0.75, 0.40, 0.50, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(1, 'CODE_QUALITY', 'MISSING_ERROR_BOUNDARY', 'info', 'src/App.tsx', 8, 'Consider adding error boundary', 'Add React Error Boundary for better error handling', 'Error boundaries prevent the entire app from crashing when a component fails', 0.80, 0.30, 0.40, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(1, 'SECURITY', 'MISSING_RATE_LIMITING', 'high', 'src/middleware/auth.ts', 30, 'Missing rate limiting', 'Implement rate limiting to prevent abuse', 'Without rate limiting, APIs are vulnerable to DoS attacks and brute force attempts', 0.85, 0.80, 0.30, 'CWE-770', 'A04: Unrestricted Resource Consumption', NULL, CURRENT_TIMESTAMP),
(1, 'CODE_QUALITY', 'HIGH_CYCLOMATIC_COMPLEXITY', 'medium', 'src/hooks/useAuth.ts', 18, 'Complex cyclomatic complexity', 'Simplify logic or extract to separate functions', 'High complexity makes code harder to maintain and test', 0.85, 0.50, 0.60, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(1, 'CODE_QUALITY', 'UNUSED_TYPE', 'low', 'src/types/index.ts', 5, 'Unused type definition', 'Remove or document the type', 'Unused code clutters the codebase and increases maintenance burden', 0.70, 0.20, 0.10, NULL, NULL, NULL, CURRENT_TIMESTAMP),

-- Vantage-Point-ML results
(2, 'SECURITY', 'SQL_INJECTION', 'critical', 'src/models/ml.py', 42, 'SQL injection vulnerability', 'Use parameterized queries or an ORM', 'User input is directly concatenated into SQL queries, allowing attackers to execute arbitrary SQL commands', 0.98, 0.99, 0.50, 'CWE-89', 'A03: Injection', 'query = "SELECT * FROM users WHERE name = ''" + user_input + "''"', CURRENT_TIMESTAMP),
(2, 'SECURITY', 'CORS_MISCONFIGURATION', 'high', 'src/api/endpoints.ts', 28, 'CORS misconfiguration', 'Restrict CORS to specific origins instead of using wildcard', 'Wildcard CORS allows any origin to access your API, potentially exposing sensitive data to malicious sites', 0.88, 0.80, 0.20, 'CWE-942', 'A05: Security Misconfiguration', 'app.use(cors({ origin: ''*'' }))', CURRENT_TIMESTAMP),
(2, 'SECURITY', 'INSUFFICIENT_INPUT_VALIDATION', 'high', 'src/utils/validation.ts', 15, 'Insufficient input validation', 'Add stricter validation rules', 'Insufficient validation can lead to security vulnerabilities and data corruption', 0.85, 0.75, 0.40, 'CWE-20', 'A01: Broken Access Control', NULL, CURRENT_TIMESTAMP),
(2, 'CODE_QUALITY', 'LARGE_COMPONENT', 'medium', 'src/components/Chart.tsx', 60, 'Large component file', 'Split into smaller components', 'Large components are harder to maintain and test', 0.80, 0.40, 0.50, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(2, 'CODE_QUALITY', 'MISSING_ERROR_HANDLING', 'medium', 'src/hooks/useData.ts', 35, 'Missing error handling', 'Add try-catch blocks for async operations', 'Unhandled exceptions can crash the application', 0.85, 0.50, 0.40, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(2, 'CODE_QUALITY', 'UNUSED_CSS', 'low', 'src/styles/theme.css', 120, 'Unused CSS classes', 'Remove unused styles', 'Unused CSS increases bundle size and maintenance burden', 0.70, 0.20, 0.20, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(2, 'CODE_QUALITY', 'MAGIC_NUMBER', 'low', 'src/config/constants.ts', 8, 'Magic number detected', 'Use named constants', 'Magic numbers reduce code readability', 0.70, 0.30, 0.20, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(2, 'CODE_QUALITY', 'MISSING_LAZY_LOADING', 'info', 'src/App.tsx', 15, 'Consider lazy loading', 'Implement code splitting for better performance', 'Lazy loading improves initial load time', 0.75, 0.40, 0.50, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(2, 'SECURITY', 'MISSING_CSRF_PROTECTION', 'medium', 'src/middleware/security.ts', 22, 'Missing CSRF protection', 'Add CSRF tokens for state-changing operations', 'CSRF attacks can force users to perform unwanted actions', 0.80, 0.70, 0.40, 'CWE-352', 'A01: Broken Access Control', NULL, CURRENT_TIMESTAMP),
(2, 'CODE_QUALITY', 'HIGH_COGNITIVE_COMPLEXITY', 'medium', 'src/services/data.ts', 50, 'High cognitive complexity', 'Refactor to improve readability', 'High cognitive complexity makes code harder to understand', 0.80, 0.50, 0.60, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(2, 'CODE_QUALITY', 'REDUNDANT_NULL_CHECK', 'low', 'src/utils/helpers.ts', 18, 'Redundant null check', 'Remove unnecessary checks', 'Redundant checks clutter the code', 0.70, 0.20, 0.10, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(2, 'CODE_QUALITY', 'MISSING_ANALYTICS', 'info', 'src/index.tsx', 5, 'Missing analytics', 'Consider adding analytics tracking', 'Analytics help understand user behavior', 0.65, 0.30, 0.40, NULL, NULL, NULL, CURRENT_TIMESTAMP),

-- hybrid_AI_coach results
(3, 'SECURITY', 'API_KEY_EXPOSURE', 'high', 'src/ai/client.ts', 20, 'API key exposed in client code', 'Move API calls to backend with proper authentication', 'API keys in client-side code are visible to anyone who inspects the browser, allowing unauthorized API usage', 0.95, 0.85, 0.70, 'CWE-798', 'A07: Identification and Authentication Failures', 'const apiKey = ''sk-abcdef123456''', CURRENT_TIMESTAMP),
(3, 'CODE_QUALITY', 'DEEP_NESTING', 'medium', 'src/components/Chat.tsx', 55, 'Deeply nested components', 'Flatten component hierarchy', 'Deep nesting makes code harder to read and maintain', 0.80, 0.40, 0.50, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(3, 'CODE_QUALITY', 'MISSING_CLEANUP', 'medium', 'src/hooks/useAI.ts', 40, 'Missing cleanup in useEffect', 'Add cleanup function to prevent memory leaks', 'Missing cleanup can cause memory leaks and unexpected behavior', 0.85, 0.60, 0.40, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(3, 'CODE_QUALITY', 'VAGUE_TYPE', 'low', 'src/types/chat.ts', 12, 'Type could be more specific', 'Use more precise TypeScript types', 'Precise types improve type safety and code clarity', 0.75, 0.30, 0.30, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(3, 'CODE_QUALITY', 'MISSING_LOADING_STATES', 'info', 'src/App.tsx', 10, 'Consider adding loading states', 'Improve UX with loading indicators', 'Loading states improve user experience', 0.70, 0.30, 0.30, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(3, 'CODE_QUALITY', 'INEFFICIENT_STRING_CONCAT', 'low', 'src/utils/format.ts', 25, 'Inefficient string concatenation', 'Use template literals', 'Template literals are more readable and efficient', 0.70, 0.20, 0.10, NULL, NULL, NULL, CURRENT_TIMESTAMP),

-- allanmichaelhender.github.io results
(4, 'SECURITY', 'EMAIL_EXPOSURE', 'high', 'src/components/Contact.tsx', 18, 'Email exposed in frontend', 'Use contact form with backend processing', 'Email addresses in frontend code can be scraped by bots, leading to spam and phishing attacks', 0.82, 0.60, 0.50, 'CWE-200', 'A01: Broken Access Control', 'const email = ''contact@example.com''', CURRENT_TIMESTAMP),
(4, 'CODE_QUALITY', 'MISSING_ALT_TEXT', 'medium', 'src/pages/About.tsx', 30, 'Missing alt text on images', 'Add descriptive alt text for accessibility', 'Alt text is essential for screen readers and SEO', 0.80, 0.40, 0.20, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(4, 'CODE_QUALITY', 'LARGE_CSS_FILE', 'low', 'src/styles/global.css', 200, 'Large CSS file', 'Consider CSS modules or styled-components', 'Large CSS files are harder to maintain', 0.70, 0.30, 0.40, NULL, NULL, NULL, CURRENT_TIMESTAMP),
(4, 'CODE_QUALITY', 'MISSING_META_TAGS', 'info', 'src/App.tsx', 12, 'Missing meta tags', 'Add SEO meta tags for better indexing', 'Meta tags improve SEO and social sharing', 0.70, 0.30, 0.20, NULL, NULL, NULL, CURRENT_TIMESTAMP);
